#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WDePOS;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WDePOSUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif








SWIFT_CLASS("_TtC8WDePOSUI25WDBarcodeScannerConstants")
@interface WDBarcodeScannerConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull scanCameraMode;)
+ (NSString * _Nonnull)scanCameraMode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double kDelayForNextBarcodeReading;)
+ (double)kDelayForNextBarcodeReading SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WDBasePopupVC;

SWIFT_PROTOCOL("_TtP8WDePOSUI21WDBasePopupCompatible_")
@protocol WDBasePopupCompatible
@property (nonatomic, strong) WDBasePopupVC * _Nullable basePopupVC;
@end

typedef SWIFT_ENUM(NSInteger, WDBasePopupType, closed) {
  WDBasePopupTypeEmptyContainer = 0,
  WDBasePopupTypeWithCalculator = 1,
  WDBasePopupTypeWithPaymentMethodSelection = 2,
  WDBasePopupTypeWithShiftMgmt = 3,
  WDBasePopupTypeWithCashRegisterSelection = 4,
  WDBasePopupTypeWithShopSelection = 5,
  WDBasePopupTypeWithSignatureRequest = 6,
  WDBasePopupTypeWithSignatureConfirmation = 7,
  WDBasePopupTypeWithBarcodeScanner = 8,
  WDBasePopupTypeWithCardApplicationSelection = 9,
};

@class UIView;
@class UILabel;
@class UIButton;
@class NSCoder;

SWIFT_CLASS("_TtC8WDePOSUI13WDBasePopupVC")
@interface WDBasePopupVC : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewBottom;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContainer;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblSubtitle;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnBack;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnCancel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnMainAction;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnSecondaryAction;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WDSaleConfiguration;

SWIFT_PROTOCOL("_TtP8WDePOSUI23WDSaleManagerCompatible_")
@protocol WDSaleManagerCompatible
@property (nonatomic, strong) WDSaleConfiguration * _Nullable saleConfiguration;
@end


@interface WDBasePopupVC (SWIFT_EXTENSION(WDePOSUI)) <WDSaleManagerCompatible>
@property (nonatomic, strong) WDSaleConfiguration * _Nullable saleConfiguration;
@end

@protocol WDCBarcodeScannerDelegate;
@protocol WDCBarcodeScannerCompatible;
@class UIImageView;
@class AVCaptureDevice;
@class NSNotification;

SWIFT_CLASS("_TtC8WDePOSUI17WDCBarcodeScanner")
@interface WDCBarcodeScanner : UIView
@property (nonatomic, weak) id <WDCBarcodeScannerDelegate> _Nullable delegate;
@property (nonatomic) BOOL inDelegateWait;
@property (nonatomic) enum AVCaptureDevicePosition cameraPosition;
@property (nonatomic, weak) UIViewController <WDCBarcodeScannerCompatible> * _Nullable parentVC;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWith:(UIViewController <WDCBarcodeScannerCompatible> * _Nonnull)viewController OBJC_DESIGNATED_INITIALIZER;
- (void)startCapture;
- (void)stopCapture;
- (void)cancelBarcodeScanning;
- (void)setInterestRectFor:(UIImageView * _Nonnull)imageView;
- (void)changeCameraMode;
- (BOOL)isTorchAvailable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isTorchAvailableForCameraOn:(enum AVCaptureDevicePosition)position SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isTorchAvaiableFor:(AVCaptureDevice * _Nonnull)camera SWIFT_WARN_UNUSED_RESULT;
- (void)toggleTorch;
- (BOOL)isTorchActive SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isTorchMatchingUiState:(BOOL)uiEnabled SWIFT_WARN_UNUSED_RESULT;
- (void)orientationDidChangeWithNotification:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class AVCaptureMetadataOutput;
@class AVMetadataObject;
@class AVCaptureConnection;

@interface WDCBarcodeScanner (SWIFT_EXTENSION(WDePOSUI)) <AVCaptureMetadataOutputObjectsDelegate>
- (void)captureOutput:(AVCaptureMetadataOutput * _Nonnull)output didOutputMetadataObjects:(NSArray<AVMetadataObject *> * _Nonnull)metadataObjects fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end


SWIFT_PROTOCOL("_TtP8WDePOSUI27WDCBarcodeScannerCompatible_")
@protocol WDCBarcodeScannerCompatible <NSObject>
@property (nonatomic, readonly, strong) UIImageView * _Null_unspecified centralHoleImageView;
@end


SWIFT_PROTOCOL("_TtP8WDePOSUI25WDCBarcodeScannerDelegate_")
@protocol WDCBarcodeScannerDelegate <NSObject>
@optional
- (void)finishedBarcodeScanWithBarcodeData:(NSString * _Nullable)barcodeData type:(NSString * _Nonnull)type;
@end


SWIFT_CLASS("_TtC8WDePOSUI19WDCCustomModalSegue")
@interface WDCCustomModalSegue : UIStoryboardSegue
- (void)perform;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nullable)identifier source:(UIViewController * _Nonnull)source destination:(UIViewController * _Nonnull)destination OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UIViewControllerAnimatedTransitioning;

@interface WDCCustomModalSegue (SWIFT_EXTENSION(WDePOSUI)) <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8WDePOSUI20WDCSidePopupAnimator")
@interface WDCSidePopupAnimator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol UIViewControllerContextTransitioning;

@interface WDCSidePopupAnimator (SWIFT_EXTENSION(WDePOSUI)) <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
@end


SWIFT_CLASS("_TtC8WDePOSUI10WDCUILabel")
@interface WDCUILabel : UILabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
- (void)drawTextInRect:(CGRect)rect;
@end


SWIFT_CLASS("_TtC8WDePOSUI14WDCancelableVC")
@interface WDCancelableVC : UIViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8WDePOSUI17WDPaymentDetailUI")
@interface WDPaymentDetailUI : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8WDePOSUI19WDPaymentMethodMask")
@interface WDPaymentMethodMask : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull cashOnly;)
+ (WDPaymentMethodMask * _Nonnull)cashOnly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull cardOnly;)
+ (WDPaymentMethodMask * _Nonnull)cardOnly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull alipayOnly;)
+ (WDPaymentMethodMask * _Nonnull)alipayOnly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull weChatOnly;)
+ (WDPaymentMethodMask * _Nonnull)weChatOnly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull standard;)
+ (WDPaymentMethodMask * _Nonnull)standard SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull qr;)
+ (WDPaymentMethodMask * _Nonnull)qr SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull all;)
+ (WDPaymentMethodMask * _Nonnull)all SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init;
/// Must expose this to Objective-C manually because
/// OptionSet.init(_: Sequence) isn’t visible to Objective-C
/// Because Sequence isn’t an Objective-C-visible type
- (nonnull instancetype)initWithAbilitiesToUnion:(NSArray<WDPaymentMethodMask *> * _Nonnull)abilitiesToUnion;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8WDePOSUI21WDPaymentNavigationVC")
@interface WDPaymentNavigationVC : UINavigationController <WDSaleManagerCompatible>
@property (nonatomic, strong) WDSaleConfiguration * _Nullable saleConfiguration;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@end

@class WDSignatureRequestVC;

SWIFT_PROTOCOL("_TtP8WDePOSUI26WDSignatureRequestDelegate_")
@protocol WDSignatureRequestDelegate
- (void)signature:(WDSignatureRequestVC * _Nonnull)signatureVC didCollectSignature:(UIImage * _Nullable)signatureImage;
@end


@interface WDPaymentNavigationVC (SWIFT_EXTENSION(WDePOSUI)) <WDSignatureRequestDelegate>
- (void)signature:(WDSignatureRequestVC * _Nonnull)signatureVC didCollectSignature:(UIImage * _Nullable)signatureImage;
@end





@class WDSelectCardApplicationVC;

SWIFT_PROTOCOL("_TtP8WDePOSUI31WDSelectCardApplicationDelegate_")
@protocol WDSelectCardApplicationDelegate
- (void)selectCardApplication:(WDSelectCardApplicationVC * _Nonnull)selectCardApplication didSelectCardApplication:(NSString * _Nonnull)cardApplication on:(NSInteger)row;
@end


@interface WDPaymentNavigationVC (SWIFT_EXTENSION(WDePOSUI)) <WDSelectCardApplicationDelegate>
- (void)selectCardApplication:(WDSelectCardApplicationVC * _Nonnull)selectCardApplication didSelectCardApplication:(NSString * _Nonnull)cardApplication on:(NSInteger)row;
@end

@class WDSelectShopVC;
@class WDShop;

SWIFT_PROTOCOL("_TtP8WDePOSUI20WDSelectShopDelegate_")
@protocol WDSelectShopDelegate
- (void)selectShop:(WDSelectShopVC * _Nonnull)selectCashRegister didSelectShop:(WDShop * _Nonnull)shop;
@end


@interface WDPaymentNavigationVC (SWIFT_EXTENSION(WDePOSUI)) <WDSelectShopDelegate>
- (void)selectShop:(WDSelectShopVC * _Nonnull)selectCashRegister didSelectShop:(WDShop * _Nonnull)shop;
@end



@class WDSelectCashRegisterVC;
@class WDCashRegister;

SWIFT_PROTOCOL("_TtP8WDePOSUI28WDSelectCashRegisterDelegate_")
@protocol WDSelectCashRegisterDelegate
- (void)selectCashRegister:(WDSelectCashRegisterVC * _Nonnull)selectCashRegister didSelectCashRegister:(WDCashRegister * _Nonnull)cashRegister;
@optional
- (void)selectCashRegisterWithDidLoadCashRegisters:(NSArray<WDCashRegister *> * _Nonnull)didLoadCashRegisters;
@end


@interface WDPaymentNavigationVC (SWIFT_EXTENSION(WDePOSUI)) <WDSelectCashRegisterDelegate>
- (void)selectCashRegister:(WDSelectCashRegisterVC * _Nonnull)selectCashRegister didSelectCashRegister:(WDCashRegister * _Nonnull)cashRegister;
- (void)selectCashRegisterWithDidLoadCashRegisters:(NSArray<WDCashRegister *> * _Nonnull)didLoadCashRegisters;
@end




SWIFT_CLASS("_TtC8WDePOSUI14WDProgressView")
@interface WDProgressView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDecimalNumber;

/// @class WDSaleConfiguration
/// @discussion  Sale configuration
/// *
SWIFT_CLASS("_TtC8WDePOSUI19WDSaleConfiguration")
@interface WDSaleConfiguration : NSObject
/// Sale Amount - if nil then user entry UI will be displayed to collect the amount
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nullable amount;
/// Currency for the sale
@property (nonatomic, readonly, copy) NSString * _Nonnull currency;
/// Tax rate for the Sale
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nullable taxRate;
/// Payment Methods
@property (nonatomic, readonly, strong) WDPaymentMethodMask * _Nonnull paymentMethods;
/// Number of decimal places for the set currency
@property (nonatomic, readonly) int16_t currencyDecimalPlaces;
/// Clear user preferences [Cash Register, Shift, User, Merchant]
@property (nonatomic) BOOL resetUserPreferences;
/// Language for the Localization of the UI elements [en,de,es] - defaults to “en”
@property (nonatomic, copy) NSString * _Nonnull language;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// @brief Default Initializer - Amount was entered by user before
/// @param amount Sale amount - if nil then user entry UI will be presented to collect the amount
/// @param currency Currency for the sale
/// @param taxRate Tax rate for the sale
/// @return the sale configuration
/// *
- (nonnull instancetype)initWithAmount:(NSDecimalNumber * _Nonnull)amount currency:(NSString * _Nonnull)currency taxRate:(NSDecimalNumber * _Nonnull)taxRate paymentMethods:(WDPaymentMethodMask * _Nonnull)paymentMethods OBJC_DESIGNATED_INITIALIZER;
/// @brief Default Initializer - Amount to be entered in the payment flow
/// @param currency Currency for the sale
/// @param taxRate Tax rate for the sale
/// @return the sale configuration
/// *
- (nonnull instancetype)initWithCurrency:(NSString * _Nonnull)currency taxRate:(NSDecimalNumber * _Nonnull)taxRate paymentMethods:(WDPaymentMethodMask * _Nonnull)paymentMethods OBJC_DESIGNATED_INITIALIZER;
/// @brief Default Initializer - Without Tax rate (don’t use when cash register management is required)
/// @param currency Currency for the sale
/// @return the sale configuration
/// *
- (nonnull instancetype)initWithCurrency:(NSString * _Nonnull)currency paymentMethods:(WDPaymentMethodMask * _Nonnull)paymentMethods OBJC_DESIGNATED_INITIALIZER;
@end



/// @class WDSaleManagerUI
/// @brief UI component of Sale Management
SWIFT_CLASS("_TtC8WDePOSUI15WDSaleManagerUI")
@interface WDSaleManagerUI : NSObject
/// copy of the completion block called at the end of Sale process
@property (nonatomic, copy) SaleCompletion _Nullable paymentCompletion;
/// copy of the progress block called upon the update from the Payment flow
@property (nonatomic, copy) PaymentProgress _Nullable paymentProgress;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// default initializer
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDSaleManagerUI * _Nonnull sharedInstance;)
+ (WDSaleManagerUI * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// @brief Start the payment process by using built in UI
/// @param progress Block bearing the information about the payment process progress
/// @param completion Block that will be called at the very end of payment flow. It provides an Saleobject (that may be nil if unauthorised) or a descriptive error
/// *
- (void)pay:(WDSaleConfiguration * _Nonnull)saleConfiguration progress:(PaymentProgress _Nonnull)progress completion:(SaleCompletion _Nullable)completion;
@end



SWIFT_CLASS("_TtC8WDePOSUI25WDSelectCardApplicationVC")
@interface WDSelectCardApplicationVC : UIViewController <WDBasePopupCompatible>
@property (nonatomic, strong) WDBasePopupVC * _Nullable basePopupVC;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;

@interface WDSelectCardApplicationVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITableViewCell;

@interface WDSelectCardApplicationVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC8WDePOSUI22WDSelectCashRegisterVC")
@interface WDSelectCashRegisterVC : WDCancelableVC <WDBasePopupCompatible>
@property (nonatomic, weak) WDBasePopupVC * _Nullable basePopupVC;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface WDSelectCashRegisterVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface WDSelectCashRegisterVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC8WDePOSUI14WDSelectShopVC")
@interface WDSelectShopVC : WDCancelableVC <WDBasePopupCompatible>
@property (nonatomic, weak) WDBasePopupVC * _Nullable basePopupVC;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface WDSelectShopVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface WDSelectShopVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC8WDePOSUI20WDSignatureRequestVC")
@interface WDSignatureRequestVC : UIViewController <WDBasePopupCompatible>
@property (nonatomic, strong) WDBasePopupVC * _Nullable basePopupVC;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8WDePOSUI11WDTouchDraw")
@interface WDTouchDraw : UIView
/// Initializes a TouchDrawView instance
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// Initializes a TouchDrawView instance
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Sets the frames of the subviews
- (void)drawRect:(CGRect)rect;
@end

@class UITouch;
@class UIEvent;

@interface WDTouchDraw (SWIFT_EXTENSION(WDePOSUI))
/// Triggered when touches begin
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
/// Triggered when touches move
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
/// Triggered whenever touches end, resulting in a newly created Stroke
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end




SWIFT_CLASS("_TtC8WDePOSUI10WDUILoader")
@interface WDUILoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8WDePOSUI17WDUserPreferences")
@interface WDUserPreferences : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WDePOS;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WDePOSUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif








SWIFT_CLASS("_TtC8WDePOSUI25WDBarcodeScannerConstants")
@interface WDBarcodeScannerConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull scanCameraMode;)
+ (NSString * _Nonnull)scanCameraMode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double kDelayForNextBarcodeReading;)
+ (double)kDelayForNextBarcodeReading SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WDBasePopupVC;

SWIFT_PROTOCOL("_TtP8WDePOSUI21WDBasePopupCompatible_")
@protocol WDBasePopupCompatible
@property (nonatomic, strong) WDBasePopupVC * _Nullable basePopupVC;
@end

typedef SWIFT_ENUM(NSInteger, WDBasePopupType, closed) {
  WDBasePopupTypeEmptyContainer = 0,
  WDBasePopupTypeWithCalculator = 1,
  WDBasePopupTypeWithPaymentMethodSelection = 2,
  WDBasePopupTypeWithShiftMgmt = 3,
  WDBasePopupTypeWithCashRegisterSelection = 4,
  WDBasePopupTypeWithShopSelection = 5,
  WDBasePopupTypeWithSignatureRequest = 6,
  WDBasePopupTypeWithSignatureConfirmation = 7,
  WDBasePopupTypeWithBarcodeScanner = 8,
  WDBasePopupTypeWithCardApplicationSelection = 9,
};

@class UIView;
@class UILabel;
@class UIButton;
@class NSCoder;

SWIFT_CLASS("_TtC8WDePOSUI13WDBasePopupVC")
@interface WDBasePopupVC : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewBottom;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContainer;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblSubtitle;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnBack;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnCancel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnMainAction;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnSecondaryAction;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WDSaleConfiguration;

SWIFT_PROTOCOL("_TtP8WDePOSUI23WDSaleManagerCompatible_")
@protocol WDSaleManagerCompatible
@property (nonatomic, strong) WDSaleConfiguration * _Nullable saleConfiguration;
@end


@interface WDBasePopupVC (SWIFT_EXTENSION(WDePOSUI)) <WDSaleManagerCompatible>
@property (nonatomic, strong) WDSaleConfiguration * _Nullable saleConfiguration;
@end

@protocol WDCBarcodeScannerDelegate;
@protocol WDCBarcodeScannerCompatible;
@class UIImageView;
@class AVCaptureDevice;
@class NSNotification;

SWIFT_CLASS("_TtC8WDePOSUI17WDCBarcodeScanner")
@interface WDCBarcodeScanner : UIView
@property (nonatomic, weak) id <WDCBarcodeScannerDelegate> _Nullable delegate;
@property (nonatomic) BOOL inDelegateWait;
@property (nonatomic) enum AVCaptureDevicePosition cameraPosition;
@property (nonatomic, weak) UIViewController <WDCBarcodeScannerCompatible> * _Nullable parentVC;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWith:(UIViewController <WDCBarcodeScannerCompatible> * _Nonnull)viewController OBJC_DESIGNATED_INITIALIZER;
- (void)startCapture;
- (void)stopCapture;
- (void)cancelBarcodeScanning;
- (void)setInterestRectFor:(UIImageView * _Nonnull)imageView;
- (void)changeCameraMode;
- (BOOL)isTorchAvailable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isTorchAvailableForCameraOn:(enum AVCaptureDevicePosition)position SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isTorchAvaiableFor:(AVCaptureDevice * _Nonnull)camera SWIFT_WARN_UNUSED_RESULT;
- (void)toggleTorch;
- (BOOL)isTorchActive SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isTorchMatchingUiState:(BOOL)uiEnabled SWIFT_WARN_UNUSED_RESULT;
- (void)orientationDidChangeWithNotification:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class AVCaptureMetadataOutput;
@class AVMetadataObject;
@class AVCaptureConnection;

@interface WDCBarcodeScanner (SWIFT_EXTENSION(WDePOSUI)) <AVCaptureMetadataOutputObjectsDelegate>
- (void)captureOutput:(AVCaptureMetadataOutput * _Nonnull)output didOutputMetadataObjects:(NSArray<AVMetadataObject *> * _Nonnull)metadataObjects fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end


SWIFT_PROTOCOL("_TtP8WDePOSUI27WDCBarcodeScannerCompatible_")
@protocol WDCBarcodeScannerCompatible <NSObject>
@property (nonatomic, readonly, strong) UIImageView * _Null_unspecified centralHoleImageView;
@end


SWIFT_PROTOCOL("_TtP8WDePOSUI25WDCBarcodeScannerDelegate_")
@protocol WDCBarcodeScannerDelegate <NSObject>
@optional
- (void)finishedBarcodeScanWithBarcodeData:(NSString * _Nullable)barcodeData type:(NSString * _Nonnull)type;
@end


SWIFT_CLASS("_TtC8WDePOSUI19WDCCustomModalSegue")
@interface WDCCustomModalSegue : UIStoryboardSegue
- (void)perform;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nullable)identifier source:(UIViewController * _Nonnull)source destination:(UIViewController * _Nonnull)destination OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UIViewControllerAnimatedTransitioning;

@interface WDCCustomModalSegue (SWIFT_EXTENSION(WDePOSUI)) <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8WDePOSUI20WDCSidePopupAnimator")
@interface WDCSidePopupAnimator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol UIViewControllerContextTransitioning;

@interface WDCSidePopupAnimator (SWIFT_EXTENSION(WDePOSUI)) <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
@end


SWIFT_CLASS("_TtC8WDePOSUI10WDCUILabel")
@interface WDCUILabel : UILabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
- (void)drawTextInRect:(CGRect)rect;
@end


SWIFT_CLASS("_TtC8WDePOSUI14WDCancelableVC")
@interface WDCancelableVC : UIViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8WDePOSUI17WDPaymentDetailUI")
@interface WDPaymentDetailUI : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8WDePOSUI19WDPaymentMethodMask")
@interface WDPaymentMethodMask : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull cashOnly;)
+ (WDPaymentMethodMask * _Nonnull)cashOnly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull cardOnly;)
+ (WDPaymentMethodMask * _Nonnull)cardOnly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull alipayOnly;)
+ (WDPaymentMethodMask * _Nonnull)alipayOnly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull weChatOnly;)
+ (WDPaymentMethodMask * _Nonnull)weChatOnly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull standard;)
+ (WDPaymentMethodMask * _Nonnull)standard SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull qr;)
+ (WDPaymentMethodMask * _Nonnull)qr SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDPaymentMethodMask * _Nonnull all;)
+ (WDPaymentMethodMask * _Nonnull)all SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init;
/// Must expose this to Objective-C manually because
/// OptionSet.init(_: Sequence) isn’t visible to Objective-C
/// Because Sequence isn’t an Objective-C-visible type
- (nonnull instancetype)initWithAbilitiesToUnion:(NSArray<WDPaymentMethodMask *> * _Nonnull)abilitiesToUnion;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8WDePOSUI21WDPaymentNavigationVC")
@interface WDPaymentNavigationVC : UINavigationController <WDSaleManagerCompatible>
@property (nonatomic, strong) WDSaleConfiguration * _Nullable saleConfiguration;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@end

@class WDSignatureRequestVC;

SWIFT_PROTOCOL("_TtP8WDePOSUI26WDSignatureRequestDelegate_")
@protocol WDSignatureRequestDelegate
- (void)signature:(WDSignatureRequestVC * _Nonnull)signatureVC didCollectSignature:(UIImage * _Nullable)signatureImage;
@end


@interface WDPaymentNavigationVC (SWIFT_EXTENSION(WDePOSUI)) <WDSignatureRequestDelegate>
- (void)signature:(WDSignatureRequestVC * _Nonnull)signatureVC didCollectSignature:(UIImage * _Nullable)signatureImage;
@end





@class WDSelectCardApplicationVC;

SWIFT_PROTOCOL("_TtP8WDePOSUI31WDSelectCardApplicationDelegate_")
@protocol WDSelectCardApplicationDelegate
- (void)selectCardApplication:(WDSelectCardApplicationVC * _Nonnull)selectCardApplication didSelectCardApplication:(NSString * _Nonnull)cardApplication on:(NSInteger)row;
@end


@interface WDPaymentNavigationVC (SWIFT_EXTENSION(WDePOSUI)) <WDSelectCardApplicationDelegate>
- (void)selectCardApplication:(WDSelectCardApplicationVC * _Nonnull)selectCardApplication didSelectCardApplication:(NSString * _Nonnull)cardApplication on:(NSInteger)row;
@end

@class WDSelectShopVC;
@class WDShop;

SWIFT_PROTOCOL("_TtP8WDePOSUI20WDSelectShopDelegate_")
@protocol WDSelectShopDelegate
- (void)selectShop:(WDSelectShopVC * _Nonnull)selectCashRegister didSelectShop:(WDShop * _Nonnull)shop;
@end


@interface WDPaymentNavigationVC (SWIFT_EXTENSION(WDePOSUI)) <WDSelectShopDelegate>
- (void)selectShop:(WDSelectShopVC * _Nonnull)selectCashRegister didSelectShop:(WDShop * _Nonnull)shop;
@end



@class WDSelectCashRegisterVC;
@class WDCashRegister;

SWIFT_PROTOCOL("_TtP8WDePOSUI28WDSelectCashRegisterDelegate_")
@protocol WDSelectCashRegisterDelegate
- (void)selectCashRegister:(WDSelectCashRegisterVC * _Nonnull)selectCashRegister didSelectCashRegister:(WDCashRegister * _Nonnull)cashRegister;
@optional
- (void)selectCashRegisterWithDidLoadCashRegisters:(NSArray<WDCashRegister *> * _Nonnull)didLoadCashRegisters;
@end


@interface WDPaymentNavigationVC (SWIFT_EXTENSION(WDePOSUI)) <WDSelectCashRegisterDelegate>
- (void)selectCashRegister:(WDSelectCashRegisterVC * _Nonnull)selectCashRegister didSelectCashRegister:(WDCashRegister * _Nonnull)cashRegister;
- (void)selectCashRegisterWithDidLoadCashRegisters:(NSArray<WDCashRegister *> * _Nonnull)didLoadCashRegisters;
@end




SWIFT_CLASS("_TtC8WDePOSUI14WDProgressView")
@interface WDProgressView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDecimalNumber;

/// @class WDSaleConfiguration
/// @discussion  Sale configuration
/// *
SWIFT_CLASS("_TtC8WDePOSUI19WDSaleConfiguration")
@interface WDSaleConfiguration : NSObject
/// Sale Amount - if nil then user entry UI will be displayed to collect the amount
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nullable amount;
/// Currency for the sale
@property (nonatomic, readonly, copy) NSString * _Nonnull currency;
/// Tax rate for the Sale
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nullable taxRate;
/// Payment Methods
@property (nonatomic, readonly, strong) WDPaymentMethodMask * _Nonnull paymentMethods;
/// Number of decimal places for the set currency
@property (nonatomic, readonly) int16_t currencyDecimalPlaces;
/// Clear user preferences [Cash Register, Shift, User, Merchant]
@property (nonatomic) BOOL resetUserPreferences;
/// Language for the Localization of the UI elements [en,de,es] - defaults to “en”
@property (nonatomic, copy) NSString * _Nonnull language;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// @brief Default Initializer - Amount was entered by user before
/// @param amount Sale amount - if nil then user entry UI will be presented to collect the amount
/// @param currency Currency for the sale
/// @param taxRate Tax rate for the sale
/// @return the sale configuration
/// *
- (nonnull instancetype)initWithAmount:(NSDecimalNumber * _Nonnull)amount currency:(NSString * _Nonnull)currency taxRate:(NSDecimalNumber * _Nonnull)taxRate paymentMethods:(WDPaymentMethodMask * _Nonnull)paymentMethods OBJC_DESIGNATED_INITIALIZER;
/// @brief Default Initializer - Amount to be entered in the payment flow
/// @param currency Currency for the sale
/// @param taxRate Tax rate for the sale
/// @return the sale configuration
/// *
- (nonnull instancetype)initWithCurrency:(NSString * _Nonnull)currency taxRate:(NSDecimalNumber * _Nonnull)taxRate paymentMethods:(WDPaymentMethodMask * _Nonnull)paymentMethods OBJC_DESIGNATED_INITIALIZER;
/// @brief Default Initializer - Without Tax rate (don’t use when cash register management is required)
/// @param currency Currency for the sale
/// @return the sale configuration
/// *
- (nonnull instancetype)initWithCurrency:(NSString * _Nonnull)currency paymentMethods:(WDPaymentMethodMask * _Nonnull)paymentMethods OBJC_DESIGNATED_INITIALIZER;
@end



/// @class WDSaleManagerUI
/// @brief UI component of Sale Management
SWIFT_CLASS("_TtC8WDePOSUI15WDSaleManagerUI")
@interface WDSaleManagerUI : NSObject
/// copy of the completion block called at the end of Sale process
@property (nonatomic, copy) SaleCompletion _Nullable paymentCompletion;
/// copy of the progress block called upon the update from the Payment flow
@property (nonatomic, copy) PaymentProgress _Nullable paymentProgress;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// default initializer
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WDSaleManagerUI * _Nonnull sharedInstance;)
+ (WDSaleManagerUI * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// @brief Start the payment process by using built in UI
/// @param progress Block bearing the information about the payment process progress
/// @param completion Block that will be called at the very end of payment flow. It provides an Saleobject (that may be nil if unauthorised) or a descriptive error
/// *
- (void)pay:(WDSaleConfiguration * _Nonnull)saleConfiguration progress:(PaymentProgress _Nonnull)progress completion:(SaleCompletion _Nullable)completion;
@end



SWIFT_CLASS("_TtC8WDePOSUI25WDSelectCardApplicationVC")
@interface WDSelectCardApplicationVC : UIViewController <WDBasePopupCompatible>
@property (nonatomic, strong) WDBasePopupVC * _Nullable basePopupVC;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;

@interface WDSelectCardApplicationVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITableViewCell;

@interface WDSelectCardApplicationVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC8WDePOSUI22WDSelectCashRegisterVC")
@interface WDSelectCashRegisterVC : WDCancelableVC <WDBasePopupCompatible>
@property (nonatomic, weak) WDBasePopupVC * _Nullable basePopupVC;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface WDSelectCashRegisterVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface WDSelectCashRegisterVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC8WDePOSUI14WDSelectShopVC")
@interface WDSelectShopVC : WDCancelableVC <WDBasePopupCompatible>
@property (nonatomic, weak) WDBasePopupVC * _Nullable basePopupVC;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface WDSelectShopVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface WDSelectShopVC (SWIFT_EXTENSION(WDePOSUI)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC8WDePOSUI20WDSignatureRequestVC")
@interface WDSignatureRequestVC : UIViewController <WDBasePopupCompatible>
@property (nonatomic, strong) WDBasePopupVC * _Nullable basePopupVC;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8WDePOSUI11WDTouchDraw")
@interface WDTouchDraw : UIView
/// Initializes a TouchDrawView instance
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// Initializes a TouchDrawView instance
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Sets the frames of the subviews
- (void)drawRect:(CGRect)rect;
@end

@class UITouch;
@class UIEvent;

@interface WDTouchDraw (SWIFT_EXTENSION(WDePOSUI))
/// Triggered when touches begin
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
/// Triggered when touches move
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
/// Triggered whenever touches end, resulting in a newly created Stroke
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end




SWIFT_CLASS("_TtC8WDePOSUI10WDUILoader")
@interface WDUILoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8WDePOSUI17WDUserPreferences")
@interface WDUserPreferences : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
