#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WDBrand",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class WDBrand;

SWIFT_CLASS("_TtC7WDBrand17ConfigurationFile")
@interface ConfigurationFile : NSObject
@property (nonatomic, strong) WDBrand * _Nonnull brand;
@property (nonatomic, readonly) BOOL isDynamicallyBranded;
+ (ConfigurationFile * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)reInitialize;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)applicationFontFamilyName SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP7WDBrand11Formattable_")
@protocol Formattable <NSObject>
- (NSString * _Nonnull)format:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)reverseValue:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)replaceCharactersIn:(NSRange)range with:(NSString * _Nonnull)replacementString for:(NSString * _Nonnull)formattedString SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

@interface NSString (SWIFT_EXTENSION(WDBrand))
- (UIColor * _Nullable)toColor SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand13PaymentMethod")
@interface PaymentMethod : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand17SupportedTerminal")
@interface SupportedTerminal : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable vendor;
@property (nonatomic, readonly, copy) NSString * _Nullable model;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class NSCoder;

/// Custom UIButton supporting branding.
/// ButtonType must be set to “custom” type in Storyboard to work properly.
SWIFT_CLASS("_TtC7WDBrand14UIButtonStyled")
@interface UIButtonStyled : UIButton
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@property (nonatomic, getter=isEnabled) BOOL enabled;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)setImage:(UIImage * _Nullable)image forState:(UIControlState)state;
@property (nonatomic) BOOL borderTop;
@property (nonatomic) BOOL borderBottom;
@property (nonatomic) NSInteger borderWidth;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, copy) NSString * _Nonnull alternativeStyleKeyPath;
@property (nonatomic, strong) UIColor * _Nullable textColorHighlighted;
@property (nonatomic, strong) UIColor * _Nullable originalBackgroundColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDictionary;

@interface UIColor (SWIFT_EXTENSION(WDBrand))
- (UIImage * _Nullable)getColoredImageWith:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)colorWithDictionary:(NSDictionary * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)lighter SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)darker SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)combineWith:(UIColor * _Nonnull)color alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand15UIControlStyled")
@interface UIControlStyled : UIControl
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


@interface UIFont (SWIFT_EXTENSION(WDBrand))
+ (UIFont * _Nullable)fontFromAppFontsBy:(NSString * _Nonnull)familyName basedOn:(UIFont * _Nonnull)baseFont SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nullable)fontFromFontFileAt:(NSString * _Nonnull)path basedOn:(UIFont * _Nonnull)baseFont SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nullable)getArrayCustomFonts SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand17UIImageViewStyled")
@interface UIImageViewStyled : UIImageView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7WDBrand39UIImageViewStyledNoIntrinsicContentSize")
@interface UIImageViewStyledNoIntrinsicContentSize : UIImageViewStyled
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand13UILabelStyled")
@interface UILabelStyled : UILabel
@property (nonatomic, copy) NSString * _Nullable customFontName;
@property (nonatomic) UIEdgeInsets customEdgeInsets;
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, strong) UIFont * _Null_unspecified font;
- (void)setAttributedText:(NSString * _Nonnull)newText bold:(BOOL)bold ofSize:(CGFloat)size;
- (void)setAttributedText:(NSString * _Nonnull)newText bold:(BOOL)bold ofSize:(CGFloat)size verticalOffset:(CGFloat)verticalOffset;
@end


SWIFT_CLASS("_TtC7WDBrand35UILabelStyledNoIntrinsicContentSize")
@interface UILabelStyledNoIntrinsicContentSize : UILabelStyled
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand18UIPickerViewStyled")
@interface UIPickerViewStyled : UIPickerView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC7WDBrand17UISearchBarStyled")
@interface UISearchBarStyled : UISearchBar
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC7WDBrand24UISegmentedControlStyled")
@interface UISegmentedControlStyled : UISegmentedControl
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithItems:(NSArray * _Nullable)items SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7WDBrand14UISwitchStyled")
@interface UISwitchStyled : UISwitch
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC7WDBrand21UITableViewCellStyled")
@interface UITableViewCellStyled : UITableViewCell
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end

@protocol UITextFieldDelegate;

SWIFT_CLASS("_TtC7WDBrand17UITextFieldStyled")
@interface UITextFieldStyled : UITextField
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
@property (nonatomic, strong) UIImage * _Nullable placeholderImage;
@property (nonatomic) BOOL canShowErrorStyle;
@property (nonatomic) BOOL isValidated;
@property (nonatomic, copy) NSString * _Nonnull customFontName;
@property (nonatomic) UIEdgeInsets edgeInsets;
@property (nonatomic, strong) UIColor * _Nullable placeholderColor;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic, strong) id <Formattable> _Nullable formatterDelegate;
@property (nonatomic, strong) id <UITextFieldDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable placeholder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (void)setFonts;
- (void)textFieldChanged:(NSNotification * _Nullable)notification;
- (void)setNeedsStyle;
- (void)setupUXSpecificProperties;
@end


@interface UITextFieldStyled (SWIFT_EXTENSION(WDBrand))
- (NSString * _Nonnull)getTextWithoutFormatting:(NSString * _Nonnull)textWithFormatting SWIFT_WARN_UNUSED_RESULT;
- (void)formatTextField:(UITextFieldStyled * _Nonnull)textField;
@end


@interface UITextFieldStyled (SWIFT_EXTENSION(WDBrand))
- (void)setValidateWhileEditing:(NSString * _Nonnull)regex;
- (void)setValidateAfterEditing:(NSString * _Nonnull)regex;
- (BOOL)validate:(BOOL)shouldHandleErrorStyle SWIFT_WARN_UNUSED_RESULT;
- (void)setErrorStyle;
- (void)resetErrorStyle;
@end


@interface UITextFieldStyled (SWIFT_EXTENSION(WDBrand)) <UITextFieldDelegate>
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP7WDBrand25UITextFieldStyledDelegate_")
@protocol UITextFieldStyledDelegate <UITextFieldDelegate>
- (void)textFieldDidChange:(UITextFieldStyled * _Nonnull)textField;
@optional
- (BOOL)textFieldShouldHandleError:(UITextFieldStyled * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC7WDBrand16UITextViewStyled")
@interface UITextViewStyled : UITextView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


@interface UIView (SWIFT_EXTENSION(WDBrand))
- (void)setCustomAccessibilityLabel:(NSString * _Nullable)accessibilityLabel;
@end


@interface UIView (SWIFT_EXTENSION(WDBrand))
- (CGFloat)getAlpha:(UIColor * _Nullable)color SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand12UIViewStyled")
@interface UIViewStyled : UIView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end

@class WDBrandConfig;
@class WDBrandUI;

SWIFT_CLASS("_TtC7WDBrand7WDBrand")
@interface WDBrand : NSObject
@property (nonatomic, readonly, strong) WDBrandConfig * _Nonnull config;
@property (nonatomic, readonly, strong) WDBrandUI * _Nonnull ui;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand19WDBrandButtonColors")
@interface WDBrandButtonColors : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull mainTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull negativeColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledIconColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledInvertedBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledInvertedTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledInvertedIconColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WDBrandGratuity;
@class WDBrandGoogleAnalytics;
@class WDBrandHelp;
@class WDBrandLegalText;

SWIFT_CLASS("_TtC7WDBrand13WDBrandConfig")
@interface WDBrandConfig : NSObject
@property (nonatomic, readonly, copy) NSArray<PaymentMethod *> * _Nonnull paymentMethods;
@property (nonatomic, readonly, copy) NSArray<SupportedTerminal *> * _Nonnull supportedTerminals;
@property (nonatomic, readonly, strong) WDBrandGratuity * _Nonnull gratuity;
@property (nonatomic, readonly, strong) WDBrandGoogleAnalytics * _Nonnull googleAnalytics;
@property (nonatomic, readonly, strong) WDBrandHelp * _Nonnull help;
@property (nonatomic, readonly) BOOL multitenderEnabled;
@property (nonatomic, readonly) BOOL printSupportEnabled;
@property (nonatomic, readonly) BOOL pistolScannerEnabled;
@property (nonatomic, readonly) BOOL tutorialQuestionMarkHidden;
@property (nonatomic, readonly) BOOL setFirstTerminalInListAsDefault;
@property (nonatomic, readonly) BOOL btTutorialAvailable;
@property (nonatomic, readonly) BOOL the3DTouchEnabled;
@property (nonatomic, readonly) BOOL showAlertWhenActivityIndicator;
@property (nonatomic, readonly) BOOL appTutorialInFirstRun;
@property (nonatomic, readonly) BOOL updateDataInAccountHidden;
@property (nonatomic, readonly) BOOL declinedReceiptBackgroundRed;
@property (nonatomic, readonly) BOOL fullRejectioReason;
@property (nonatomic, readonly) BOOL mandatoryUniqueTax;
@property (nonatomic, readonly) BOOL flatDiscountUIEnabled;
@property (nonatomic, readonly) BOOL memberCardsWithExtraEACode;
@property (nonatomic, readonly) BOOL emailReceiptEnabled;
@property (nonatomic, readonly) BOOL smsReceiptEnabled;
@property (nonatomic, readonly) BOOL numpadInputHidden;
@property (nonatomic, readonly) BOOL refundOnlyThroughBackend;
@property (nonatomic, readonly) BOOL cashDrawerButtonEnabled;
@property (nonatomic, readonly) BOOL refundOverReversalAlways;
@property (nonatomic, readonly) BOOL cardTransacNeverReturnable;
@property (nonatomic, readonly) BOOL hideServiceCharge;
@property (nonatomic, readonly) BOOL hideGratuity;
@property (nonatomic, readonly) BOOL hideStatistics;
@property (nonatomic, readonly) BOOL customerReceipt;
@property (nonatomic, readonly) BOOL inventoryEnabled;
@property (nonatomic, readonly) BOOL inventoryEditable;
@property (nonatomic, readonly) BOOL quickClerkLoginEnabled;
@property (nonatomic, readonly) BOOL rememberingSingleUserEnabled;
@property (nonatomic, readonly) BOOL rememberingMultipleUsersEnabled;
@property (nonatomic, readonly) BOOL automaticPrintingEnabled;
@property (nonatomic, readonly) BOOL wideImagesInCustomerReceipt;
@property (nonatomic, readonly) BOOL signatureButtonsWithIcons;
@property (nonatomic, readonly) BOOL sendingReceiptAlways;
@property (nonatomic, readonly) BOOL bigUIMessages;
@property (nonatomic, readonly, copy) NSString * _Nullable addItemButtonLocalisedName;
@property (nonatomic, readonly, copy) NSString * _Nullable clearListButtonLocalisedName;
@property (nonatomic, readonly, copy) NSString * _Nonnull supportAppName;
@property (nonatomic, readonly, copy) NSString * _Nonnull owningCompanyName;
@property (nonatomic, readonly, copy) NSString * _Nonnull registrationUrl;
@property (nonatomic, readonly, copy) NSArray<WDBrandLegalText *> * _Nonnull legalText;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull languageList;
@property (nonatomic, readonly, copy) NSString * _Nullable uiAppFonts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand22WDBrandGoogleAnalytics")
@interface WDBrandGoogleAnalytics : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable key;
@property (nonatomic, readonly, copy) NSString * _Nullable secondaryKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand15WDBrandGratuity")
@interface WDBrandGratuity : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rates;
@property (nonatomic, readonly, copy) NSString * _Nonnull tax;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand11WDBrandHelp")
@interface WDBrandHelp : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull faqUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull dataProtectionUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull legalNoticeUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull termsAndConditionsUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull websiteUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand16WDBrandLegalText")
@interface WDBrandLegalText : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable en;
@property (nonatomic, readonly, copy) NSString * _Nullable de;
@property (nonatomic, readonly, copy) NSString * _Nullable es;
@property (nonatomic, readonly, copy) NSString * _Nullable zhHans;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand14WDBrandOpacity")
@interface WDBrandOpacity : NSObject
@property (nonatomic, readonly) CGFloat primary;
@property (nonatomic, readonly) CGFloat secondary;
@property (nonatomic, readonly) CGFloat placeholder;
@property (nonatomic, readonly) CGFloat disabled;
@property (nonatomic, readonly) CGFloat highlighted;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand17WDBrandTextColors")
@interface WDBrandTextColors : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull mainColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull lightTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledTextColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand24WDBrandTransactionColors")
@interface WDBrandTransactionColors : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull positive;
@property (nonatomic, readonly, strong) UIColor * _Nonnull incomplete;
@property (nonatomic, readonly, strong) UIColor * _Nonnull refunded;
@property (nonatomic, readonly, strong) UIColor * _Nonnull failed;
@property (nonatomic, readonly, strong) UIColor * _Nonnull canceled;
@property (nonatomic, readonly, strong) UIColor * _Nonnull reversed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand9WDBrandUI")
@interface WDBrandUI : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull mainAccentColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull solidSeparatorColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull infoColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull successColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull warningColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull errorColor;
@property (nonatomic, readonly, strong) WDBrandTextColors * _Nonnull textColors;
@property (nonatomic, readonly, strong) WDBrandButtonColors * _Nonnull buttonColors;
@property (nonatomic, readonly, strong) WDBrandTransactionColors * _Nonnull transactionColors;
@property (nonatomic, readonly, strong) WDBrandOpacity * _Nonnull opacity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand23WDCInputWithErrorStyled")
@interface WDCInputWithErrorStyled : UIStackView
@property (nonatomic, copy) NSString * _Nonnull textFieldStyleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull textFieldTranslationKey;
@property (nonatomic, strong) UITextFieldStyled * _Nonnull textField;
@property (nonatomic) CGFloat textFieldCornerRadius;
@property (nonatomic, strong) UILabelStyled * _Nonnull errorLabel;
@property (nonatomic, strong) UIColor * _Nonnull errorColor;
@property (nonatomic, readonly) BOOL hasError;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)showError;
- (void)showErrorWith:(NSString * _Nullable)text;
- (void)hideError;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WDBrand",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class WDBrand;

SWIFT_CLASS("_TtC7WDBrand17ConfigurationFile")
@interface ConfigurationFile : NSObject
@property (nonatomic, strong) WDBrand * _Nonnull brand;
@property (nonatomic, readonly) BOOL isDynamicallyBranded;
+ (ConfigurationFile * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)reInitialize;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)applicationFontFamilyName SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP7WDBrand11Formattable_")
@protocol Formattable <NSObject>
- (NSString * _Nonnull)format:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)reverseValue:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)replaceCharactersIn:(NSRange)range with:(NSString * _Nonnull)replacementString for:(NSString * _Nonnull)formattedString SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

@interface NSString (SWIFT_EXTENSION(WDBrand))
- (UIColor * _Nullable)toColor SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand13PaymentMethod")
@interface PaymentMethod : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand17SupportedTerminal")
@interface SupportedTerminal : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable vendor;
@property (nonatomic, readonly, copy) NSString * _Nullable model;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class NSCoder;

/// Custom UIButton supporting branding.
/// ButtonType must be set to “custom” type in Storyboard to work properly.
SWIFT_CLASS("_TtC7WDBrand14UIButtonStyled")
@interface UIButtonStyled : UIButton
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@property (nonatomic, getter=isEnabled) BOOL enabled;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)setImage:(UIImage * _Nullable)image forState:(UIControlState)state;
@property (nonatomic) BOOL borderTop;
@property (nonatomic) BOOL borderBottom;
@property (nonatomic) NSInteger borderWidth;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, copy) NSString * _Nonnull alternativeStyleKeyPath;
@property (nonatomic, strong) UIColor * _Nullable textColorHighlighted;
@property (nonatomic, strong) UIColor * _Nullable originalBackgroundColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDictionary;

@interface UIColor (SWIFT_EXTENSION(WDBrand))
- (UIImage * _Nullable)getColoredImageWith:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)colorWithDictionary:(NSDictionary * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)lighter SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)darker SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)combineWith:(UIColor * _Nonnull)color alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand15UIControlStyled")
@interface UIControlStyled : UIControl
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


@interface UIFont (SWIFT_EXTENSION(WDBrand))
+ (UIFont * _Nullable)fontFromAppFontsBy:(NSString * _Nonnull)familyName basedOn:(UIFont * _Nonnull)baseFont SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nullable)fontFromFontFileAt:(NSString * _Nonnull)path basedOn:(UIFont * _Nonnull)baseFont SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nullable)getArrayCustomFonts SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand17UIImageViewStyled")
@interface UIImageViewStyled : UIImageView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7WDBrand39UIImageViewStyledNoIntrinsicContentSize")
@interface UIImageViewStyledNoIntrinsicContentSize : UIImageViewStyled
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand13UILabelStyled")
@interface UILabelStyled : UILabel
@property (nonatomic, copy) NSString * _Nullable customFontName;
@property (nonatomic) UIEdgeInsets customEdgeInsets;
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, strong) UIFont * _Null_unspecified font;
- (void)setAttributedText:(NSString * _Nonnull)newText bold:(BOOL)bold ofSize:(CGFloat)size;
- (void)setAttributedText:(NSString * _Nonnull)newText bold:(BOOL)bold ofSize:(CGFloat)size verticalOffset:(CGFloat)verticalOffset;
@end


SWIFT_CLASS("_TtC7WDBrand35UILabelStyledNoIntrinsicContentSize")
@interface UILabelStyledNoIntrinsicContentSize : UILabelStyled
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand18UIPickerViewStyled")
@interface UIPickerViewStyled : UIPickerView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC7WDBrand17UISearchBarStyled")
@interface UISearchBarStyled : UISearchBar
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC7WDBrand24UISegmentedControlStyled")
@interface UISegmentedControlStyled : UISegmentedControl
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithItems:(NSArray * _Nullable)items SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7WDBrand14UISwitchStyled")
@interface UISwitchStyled : UISwitch
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC7WDBrand21UITableViewCellStyled")
@interface UITableViewCellStyled : UITableViewCell
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end

@protocol UITextFieldDelegate;

SWIFT_CLASS("_TtC7WDBrand17UITextFieldStyled")
@interface UITextFieldStyled : UITextField
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
@property (nonatomic, strong) UIImage * _Nullable placeholderImage;
@property (nonatomic) BOOL canShowErrorStyle;
@property (nonatomic) BOOL isValidated;
@property (nonatomic, copy) NSString * _Nonnull customFontName;
@property (nonatomic) UIEdgeInsets edgeInsets;
@property (nonatomic, strong) UIColor * _Nullable placeholderColor;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic, strong) id <Formattable> _Nullable formatterDelegate;
@property (nonatomic, strong) id <UITextFieldDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable placeholder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (void)setFonts;
- (void)textFieldChanged:(NSNotification * _Nullable)notification;
- (void)setNeedsStyle;
- (void)setupUXSpecificProperties;
@end


@interface UITextFieldStyled (SWIFT_EXTENSION(WDBrand))
- (NSString * _Nonnull)getTextWithoutFormatting:(NSString * _Nonnull)textWithFormatting SWIFT_WARN_UNUSED_RESULT;
- (void)formatTextField:(UITextFieldStyled * _Nonnull)textField;
@end


@interface UITextFieldStyled (SWIFT_EXTENSION(WDBrand))
- (void)setValidateWhileEditing:(NSString * _Nonnull)regex;
- (void)setValidateAfterEditing:(NSString * _Nonnull)regex;
- (BOOL)validate:(BOOL)shouldHandleErrorStyle SWIFT_WARN_UNUSED_RESULT;
- (void)setErrorStyle;
- (void)resetErrorStyle;
@end


@interface UITextFieldStyled (SWIFT_EXTENSION(WDBrand)) <UITextFieldDelegate>
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP7WDBrand25UITextFieldStyledDelegate_")
@protocol UITextFieldStyledDelegate <UITextFieldDelegate>
- (void)textFieldDidChange:(UITextFieldStyled * _Nonnull)textField;
@optional
- (BOOL)textFieldShouldHandleError:(UITextFieldStyled * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC7WDBrand16UITextViewStyled")
@interface UITextViewStyled : UITextView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


@interface UIView (SWIFT_EXTENSION(WDBrand))
- (void)setCustomAccessibilityLabel:(NSString * _Nullable)accessibilityLabel;
@end


@interface UIView (SWIFT_EXTENSION(WDBrand))
- (CGFloat)getAlpha:(UIColor * _Nullable)color SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand12UIViewStyled")
@interface UIViewStyled : UIView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end

@class WDBrandConfig;
@class WDBrandUI;

SWIFT_CLASS("_TtC7WDBrand7WDBrand")
@interface WDBrand : NSObject
@property (nonatomic, readonly, strong) WDBrandConfig * _Nonnull config;
@property (nonatomic, readonly, strong) WDBrandUI * _Nonnull ui;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand19WDBrandButtonColors")
@interface WDBrandButtonColors : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull mainTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull negativeColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledIconColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledInvertedBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledInvertedTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledInvertedIconColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WDBrandGratuity;
@class WDBrandGoogleAnalytics;
@class WDBrandHelp;
@class WDBrandLegalText;

SWIFT_CLASS("_TtC7WDBrand13WDBrandConfig")
@interface WDBrandConfig : NSObject
@property (nonatomic, readonly, copy) NSArray<PaymentMethod *> * _Nonnull paymentMethods;
@property (nonatomic, readonly, copy) NSArray<SupportedTerminal *> * _Nonnull supportedTerminals;
@property (nonatomic, readonly, strong) WDBrandGratuity * _Nonnull gratuity;
@property (nonatomic, readonly, strong) WDBrandGoogleAnalytics * _Nonnull googleAnalytics;
@property (nonatomic, readonly, strong) WDBrandHelp * _Nonnull help;
@property (nonatomic, readonly) BOOL multitenderEnabled;
@property (nonatomic, readonly) BOOL printSupportEnabled;
@property (nonatomic, readonly) BOOL pistolScannerEnabled;
@property (nonatomic, readonly) BOOL tutorialQuestionMarkHidden;
@property (nonatomic, readonly) BOOL setFirstTerminalInListAsDefault;
@property (nonatomic, readonly) BOOL btTutorialAvailable;
@property (nonatomic, readonly) BOOL the3DTouchEnabled;
@property (nonatomic, readonly) BOOL showAlertWhenActivityIndicator;
@property (nonatomic, readonly) BOOL appTutorialInFirstRun;
@property (nonatomic, readonly) BOOL updateDataInAccountHidden;
@property (nonatomic, readonly) BOOL declinedReceiptBackgroundRed;
@property (nonatomic, readonly) BOOL fullRejectioReason;
@property (nonatomic, readonly) BOOL mandatoryUniqueTax;
@property (nonatomic, readonly) BOOL flatDiscountUIEnabled;
@property (nonatomic, readonly) BOOL memberCardsWithExtraEACode;
@property (nonatomic, readonly) BOOL emailReceiptEnabled;
@property (nonatomic, readonly) BOOL smsReceiptEnabled;
@property (nonatomic, readonly) BOOL numpadInputHidden;
@property (nonatomic, readonly) BOOL refundOnlyThroughBackend;
@property (nonatomic, readonly) BOOL cashDrawerButtonEnabled;
@property (nonatomic, readonly) BOOL refundOverReversalAlways;
@property (nonatomic, readonly) BOOL cardTransacNeverReturnable;
@property (nonatomic, readonly) BOOL hideServiceCharge;
@property (nonatomic, readonly) BOOL hideGratuity;
@property (nonatomic, readonly) BOOL hideStatistics;
@property (nonatomic, readonly) BOOL customerReceipt;
@property (nonatomic, readonly) BOOL inventoryEnabled;
@property (nonatomic, readonly) BOOL inventoryEditable;
@property (nonatomic, readonly) BOOL quickClerkLoginEnabled;
@property (nonatomic, readonly) BOOL rememberingSingleUserEnabled;
@property (nonatomic, readonly) BOOL rememberingMultipleUsersEnabled;
@property (nonatomic, readonly) BOOL automaticPrintingEnabled;
@property (nonatomic, readonly) BOOL wideImagesInCustomerReceipt;
@property (nonatomic, readonly) BOOL signatureButtonsWithIcons;
@property (nonatomic, readonly) BOOL sendingReceiptAlways;
@property (nonatomic, readonly) BOOL bigUIMessages;
@property (nonatomic, readonly, copy) NSString * _Nullable addItemButtonLocalisedName;
@property (nonatomic, readonly, copy) NSString * _Nullable clearListButtonLocalisedName;
@property (nonatomic, readonly, copy) NSString * _Nonnull supportAppName;
@property (nonatomic, readonly, copy) NSString * _Nonnull owningCompanyName;
@property (nonatomic, readonly, copy) NSString * _Nonnull registrationUrl;
@property (nonatomic, readonly, copy) NSArray<WDBrandLegalText *> * _Nonnull legalText;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull languageList;
@property (nonatomic, readonly, copy) NSString * _Nullable uiAppFonts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand22WDBrandGoogleAnalytics")
@interface WDBrandGoogleAnalytics : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable key;
@property (nonatomic, readonly, copy) NSString * _Nullable secondaryKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand15WDBrandGratuity")
@interface WDBrandGratuity : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rates;
@property (nonatomic, readonly, copy) NSString * _Nonnull tax;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand11WDBrandHelp")
@interface WDBrandHelp : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull faqUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull dataProtectionUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull legalNoticeUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull termsAndConditionsUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull websiteUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand16WDBrandLegalText")
@interface WDBrandLegalText : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable en;
@property (nonatomic, readonly, copy) NSString * _Nullable de;
@property (nonatomic, readonly, copy) NSString * _Nullable es;
@property (nonatomic, readonly, copy) NSString * _Nullable zhHans;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand14WDBrandOpacity")
@interface WDBrandOpacity : NSObject
@property (nonatomic, readonly) CGFloat primary;
@property (nonatomic, readonly) CGFloat secondary;
@property (nonatomic, readonly) CGFloat placeholder;
@property (nonatomic, readonly) CGFloat disabled;
@property (nonatomic, readonly) CGFloat highlighted;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand17WDBrandTextColors")
@interface WDBrandTextColors : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull mainColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull lightTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull disabledTextColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand24WDBrandTransactionColors")
@interface WDBrandTransactionColors : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull positive;
@property (nonatomic, readonly, strong) UIColor * _Nonnull incomplete;
@property (nonatomic, readonly, strong) UIColor * _Nonnull refunded;
@property (nonatomic, readonly, strong) UIColor * _Nonnull failed;
@property (nonatomic, readonly, strong) UIColor * _Nonnull canceled;
@property (nonatomic, readonly, strong) UIColor * _Nonnull reversed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand9WDBrandUI")
@interface WDBrandUI : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull mainAccentColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull solidSeparatorColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull infoColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull successColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull warningColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull errorColor;
@property (nonatomic, readonly, strong) WDBrandTextColors * _Nonnull textColors;
@property (nonatomic, readonly, strong) WDBrandButtonColors * _Nonnull buttonColors;
@property (nonatomic, readonly, strong) WDBrandTransactionColors * _Nonnull transactionColors;
@property (nonatomic, readonly, strong) WDBrandOpacity * _Nonnull opacity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand23WDCInputWithErrorStyled")
@interface WDCInputWithErrorStyled : UIStackView
@property (nonatomic, copy) NSString * _Nonnull textFieldStyleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull textFieldTranslationKey;
@property (nonatomic, strong) UITextFieldStyled * _Nonnull textField;
@property (nonatomic) CGFloat textFieldCornerRadius;
@property (nonatomic, strong) UILabelStyled * _Nonnull errorLabel;
@property (nonatomic, strong) UIColor * _Nonnull errorColor;
@property (nonatomic, readonly) BOOL hasError;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)showError;
- (void)showErrorWith:(NSString * _Nullable)text;
- (void)hideError;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
