platform :ios, :deployment_target => '9.0'
use_frameworks!

def shared_dependencies
    pod 'WDePOS/All', :path => '../'
    pod 'WDBrand', :path => '../'
    pod 'INTULocationManager'
    pod 'CocoaLumberjack', '~> 3.0'
    pod 'CocoaLumberjack/Swift'
end

target 'ePosDemo' do
    shared_dependencies
end


target 'Tests' do
    shared_dependencies
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
            config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['$(FRAMEWORK_SEARCH_PATHS)']
            if config.name != 'Release'
                #config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG_LOGS=1']
            end
        end
    end
end
