platform :ios, '9.0'
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

project 'eClear.xcodeproj'

def shared_dependencies
     pod 'WDePOS/All', :path => '../'
     pod 'NotificationBannerSwift', '~> 1.4.5'
	 pod 'TWMessageBarManager'
end

target 'eClear' do
    shared_dependencies
end
