// Generated by Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WDBrand",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIColor;
enum TransactionStatus : NSInteger;
@class UIImage;

SWIFT_CLASS("_TtC7WDBrand14BrandingHelper")
@interface BrandingHelper : NSObject
@property (nonatomic) UIStatusBarStyle statusBarStyle;
@property (nonatomic) NSInteger taxAmountReadingFailuresCount;
@property (nonatomic) BOOL paymentTimerOngoing;
@property (nonatomic) BOOL waitingForPaymentTimer;
@property (nonatomic) BOOL isTutorialQuestionMarkButtonHidden;
@property (nonatomic) BOOL isBTTutorialAvailable;
@property (nonatomic) BOOL isAppTutorialInFirstRun;
@property (nonatomic) BOOL isUpdateDataInAccountHidden;
@property (nonatomic) BOOL isHasDeclinedReceiptBackgroundRed;
@property (nonatomic) BOOL isFullRejectioReason;
@property (nonatomic) BOOL isFirstTerminalAsDefault;
@property (nonatomic) BOOL isSendingReceiptAlways;
@property (nonatomic) BOOL isBigUIMessages;
@property (nonatomic) BOOL isRememberedUsers;
@property (nonatomic) BOOL isMandatoryTax;
@property (nonatomic) BOOL isCashDrawerButtonEnabled;
@property (nonatomic) BOOL isRefundOverReversalAlways;
@property (nonatomic) BOOL isCardTransacNeverReturnable;
@property (nonatomic) BOOL isServiceChargeHidden;
@property (nonatomic) BOOL is3DTouchEnabled;
@property (nonatomic) BOOL isGratuityHidden;
@property (nonatomic) BOOL isRememberingPassword;
@property (nonatomic) BOOL isHasMemberCardsWithExtraEACode;
@property (nonatomic) BOOL isRefundOnlyThroughBackend;
@property (nonatomic) BOOL isSendEmailReceiptEnabled;
@property (nonatomic) BOOL isFlatDiscountUIEnabled;
@property (nonatomic) BOOL isSendSMSReceiptEnabled;
@property (nonatomic) BOOL isNumpadHidden;
@property (nonatomic) BOOL isShowingAlert;
@property (nonatomic) BOOL isTaxNameFromConfig;
@property (nonatomic) BOOL isLocalisingButtons;
@property (nonatomic) BOOL isShowAlertWhenActivityIndicator;
@property (nonatomic) BOOL isSignatureButtonsWithIcons;
@property (nonatomic) BOOL isStatisticsHidden;
@property (nonatomic) BOOL isShowingCustomerReceipt;
@property (nonatomic) BOOL isInventoryEditable;
@property (nonatomic) BOOL isInventoryEnabled;
@property (nonatomic) BOOL isPistolScannerEnabled;
@property (nonatomic) BOOL isQuickClerkLoginEnabled;
@property (nonatomic) BOOL isAutomaticPrintingEnabled;
@property (nonatomic) BOOL isShowingWideImagesInCustomerReceipt;
@property (nonatomic) BOOL signatureButtonsWithIcons;
@property (nonatomic, copy) NSString * _Nullable googleAnalyticsKey;
@property (nonatomic, copy) NSString * _Nullable googleAnalyticsSecondaryKey;
@property (nonatomic, copy) NSString * _Nullable localisedTaxRateName;
@property (nonatomic, copy) NSString * _Nullable localisedTaxName;
@property (nonatomic, copy) NSString * _Nullable supportAppName;
@property (nonatomic, copy) NSString * _Nullable owningCompanyName;
@property (nonatomic, copy) NSString * _Nullable legalText;
@property (nonatomic, copy) NSString * _Nullable registrationURL;
@property (nonatomic, copy) NSString * _Nullable addItemBtnLocalisedText;
@property (nonatomic, copy) NSString * _Nullable clearListBtnLocalisedText;
@property (nonatomic, copy) NSString * _Nullable faqUrl;
@property (nonatomic, copy) NSString * _Nullable dataProtectionUrl;
@property (nonatomic, copy) NSString * _Nullable legalNoticeUrl;
@property (nonatomic, copy) NSString * _Nullable termsAndConditionsUrl;
@property (nonatomic, copy) NSString * _Nullable websiteUrl;
@property (nonatomic) id _Nullable alertController;
@property (nonatomic, copy) NSDate * _Nullable accountCreationDate;
@property (nonatomic, strong) UIColor * _Nullable iPadTableAndSelectionColor;
@property (nonatomic, copy) NSArray * _Nullable languages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BrandingHelper * _Nonnull sharedInstance;)
+ (BrandingHelper * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)getExtraConfigValues;
- (NSArray * _Nullable)getActivityIndicatorFrameImages SWIFT_WARN_UNUSED_RESULT;
- (void)loadAnimationFramesWithKeyPath:(NSString * _Nullable)keyPath;
+ (UIColor * _Nullable)getColorFromConfigByKeyPath:(NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)mainBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)basketBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)tableSeparatorColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)tableSectionTitleColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)commonTitleColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)mainBrandColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)inventoryBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)inventoryDescriptionLblColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)numpadTaxCustomButtonsColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)errorBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)infoBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)warningBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)generalViewBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)approvedTransactionColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)reversedTransactionColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)rejectedTransactionColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)refundedTransactionColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)incompleteTransactionColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)receiptBackground SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)settingsBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)innerRadialGradiantError SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)outerRadialGradiantError SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)upperBezierGradiantError SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)lowerBezierGradiantError SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)commonTitleLightColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)transactionColor:(enum TransactionStatus)transactionStatus SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageWithColor:(UIColor * _Nullable)color andHeight:(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
+ (void)setGlobalStyle;
- (NSString * _Nonnull)getRegistrationURL SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getLegalTextForLanguage:(NSString * _Nullable)language SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getLocalisedTaxRateName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getLocalisedTaxName SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getFullRejectioReason SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneLoginButtonsTextColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneLoginButtonsBkgColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)iphoneNumpadBackgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadTotalValueLabelColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadDescriptionLabelColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadPlaceholderTextColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadQtyLabelColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadTaxButtonsBkgColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadTaxButtonsBkgSelectedColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadTaxButtonsTextColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadTaxButtonsTextSelectedColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadNumButtonsBkgColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadNumButtonsTextColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadNumButtonsTextSelectedColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)iphoneNumpadAndInventoryBkgColor SWIFT_WARN_UNUSED_RESULT;
@end

@class NSDictionary;

SWIFT_CLASS("_TtC7WDBrand17ConfigurationFile")
@interface ConfigurationFile : NSObject
@property (nonatomic, strong) NSDictionary * _Nonnull brand;
@property (nonatomic, copy) NSArray * _Nonnull backendsArray;
+ (ConfigurationFile * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (id _Nullable)dictionaryValueTypeForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)applicationFontFamilyName SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getBoolValue:(NSString * _Nonnull)keyPath SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getSafeStringValue:(NSString * _Nonnull)keyPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getBoolValueAsIntIfExist:(NSString * _Nonnull)keyPath SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)getColorFromConfigByKeyPath:(NSString * _Nonnull)keyPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP7WDBrand11Formattable_")
@protocol Formattable <NSObject>
- (NSString * _Nonnull)format:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)reverseValue:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)replaceCharactersIn:(NSRange)range with:(NSString * _Nonnull)replacementString for:(NSString * _Nonnull)formattedString SWIFT_WARN_UNUSED_RESULT;
@end




@interface NSString (SWIFT_EXTENSION(WDBrand))
- (NSInteger)instr:(NSString * _Nullable)substring SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)stringByRemovingControlCharacters SWIFT_WARN_UNUSED_RESULT;
- (BOOL)containsHTMLInjectionCharacters SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)stringByAddingPercentEncoding SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getInitials SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)stringByRemovingHTMLInjectionCharacters SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)toColor SWIFT_WARN_UNUSED_RESULT;
@end

@class UITouch;
@class UIEvent;
@class NSCoder;

SWIFT_CLASS("_TtC7WDBrand25SegmentedControlResizable")
@interface SegmentedControlResizable : UISegmentedControl
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithItems:(NSArray * _Nullable)items OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TransactionStatus, closed) {
  TransactionStatusTransactionAccepted = 0,
  TransactionStatusTransactionRejected = 1,
  TransactionStatusTransactionCanceled = 2,
  TransactionStatusTransactionReimbursed = 3,
  TransactionStatusTransactionPartially_Reimbursed = 4,
  TransactionStatusTransactionUnconfirmed = 5,
};


@interface UIAlertController (SWIFT_EXTENSION(WDBrand))
- (void)customViewWillAppear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC7WDBrand14UIButtonStyled")
@interface UIButtonStyled : UIButton
@property (nonatomic, copy) NSString * _Nonnull customFontName;
@property (nonatomic, strong) UIColor * _Nullable originalBackgroundColor;
@property (nonatomic, strong) UIColor * _Nullable originalBackgroundHighlightColor;
@property (nonatomic, strong) UIColor * _Nullable originalBackgroundSelectedColor;
@property (nonatomic, strong) UIColor * _Nullable originalBackgroundDisabledColor;
@property (nonatomic, strong) UIColor * _Nullable textColorHighlighted;
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull alternativeStyleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
@property (nonatomic) BOOL hasSegmentedControlBehaviour;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL borderTop;
@property (nonatomic) BOOL borderLeft;
@property (nonatomic) BOOL borderRight;
@property (nonatomic) BOOL borderBottom;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, strong) UIColor * _Nullable textColorSelected;
@property (nonatomic, strong) UIColor * _Nullable textColorDisabled;
@property (nonatomic, strong) UIColor * _Nullable shadowColor;
@property (nonatomic, strong) UIColor * _Nullable shadowColorHighlighted;
@property (nonatomic, strong) UIColor * _Nullable shadowColorSelected;
@property (nonatomic, strong) UIColor * _Nullable shadowColorDisabled;
@property (nonatomic, copy) NSString * _Nonnull backgroundImage;
@property (nonatomic, copy) NSString * _Nonnull backgroundImageSelected;
@property (nonatomic, copy) NSString * _Nonnull backgroundImageHighlighted;
@property (nonatomic, copy) NSString * _Nonnull backgroundImageDisabled;
@property (nonatomic, copy) NSString * _Nonnull backgroundColorHighlighted;
@property (nonatomic, copy) NSString * _Nonnull image;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (void)drawRect:(CGRect)rect;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@property (nonatomic, getter=isSelected) BOOL selected;
@property (nonatomic, getter=isEnabled) BOOL enabled;
- (void)setNeedsStyle;
- (void)setBackgroundColorForAllStates:(UIColor * _Nonnull)color;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UICollectionViewLayout;

SWIFT_CLASS("_TtC7WDBrand22UICollectionViewStyled")
@interface UICollectionViewStyled : UICollectionView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(WDBrand))
+ (UIColor * _Nullable)colorWithDictionary:(NSDictionary * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)lighter SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)darker SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand15UIControlStyled")
@interface UIControlStyled : UIControl
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


@interface UIFont (SWIFT_EXTENSION(WDBrand))
+ (UIFont * _Nullable)fontFromAppFontsBy:(NSString * _Nonnull)familyName basedOn:(UIFont * _Nonnull)baseFont SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nullable)fontFromFontFileAt:(NSString * _Nonnull)path basedOn:(UIFont * _Nonnull)baseFont SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nullable)getArrayCustomFonts SWIFT_WARN_UNUSED_RESULT;
@end

@class CALayer;

@interface UIImage (SWIFT_EXTENSION(WDBrand))
+ (UIImage * _Nullable)imageFromText:(NSString * _Nonnull)text of:(CGSize)ofSize andFontSize:(CGFloat)fontSize andTextColor:(UIColor * _Nullable)textColor SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)base64PNG:(UIImage * _Nonnull)imageToConvert SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageFromPDFFile:(NSString * _Nonnull)pdfPath SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageFromPDFFile:(NSString * _Nonnull)pdfPath targetSize:(CGSize)targetSize SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageFromPDFFile:(NSString * _Nonnull)pdfPath withWidth:(CGFloat)targetWidth SWIFT_WARN_UNUSED_RESULT;
+ (void)drawPDFPageInRect:(CGPDFPageRef _Nonnull)pageRef destinationRect:(CGRect)destinationRect;
- (UIImage * _Nullable)scaledToScale:(CGFloat)scale SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageFrom:(CALayer * _Nonnull)layer SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)resizeTo:(CGSize)newSize SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)imageBlackAndWhite SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)makeResizedImage:(CGSize)newSize quality:(CGInterpolationQuality)interpolationQuality preserveAspectRatio:(BOOL)preserveAspectRatio SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageDrawAndMaskWithColor:(UIImage * _Nullable)image color:(UIColor * _Nullable)color SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)maskAllColoursButBlackIn:(UIImage * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageWithBorderFrom:(UIImage * _Nonnull)source border:(CGFloat)border borderColor:(UIColor * _Nullable)borderColor SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageMaskWithColor:(UIImage * _Nullable)image color:(UIColor * _Nullable)color SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)cutOut:(CGRect)rect cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageFrom:(UIColor * _Nonnull)color for:(CGSize)size withCornerRadius:(CGFloat)radius SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)merge:(UIImage * _Nullable)image SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)merge:(UIImage * _Nullable)image at:(CGPoint)point SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC7WDBrand17UIImageViewStyled")
@interface UIImageViewStyled : UIImageView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7WDBrand39UIImageViewStyledNoIntrinsicContentSize")
@interface UIImageViewStyledNoIntrinsicContentSize : UIImageViewStyled
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand13UILabelStyled")
@interface UILabelStyled : UILabel
@property (nonatomic, copy) NSString * _Nullable customFontName;
@property (nonatomic) CGRect customFrame;
@property (nonatomic) UIEdgeInsets customEdgeInsets;
@property (nonatomic, copy) NSString * _Nullable styleKeyPath;
@property (nonatomic, copy) NSString * _Nullable translationKey;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, strong) UIFont * _Null_unspecified font;
- (void)setNeedsStyle;
- (void)setupUXSpecificProperties;
- (void)setAttributedText:(NSString * _Nonnull)newText bold:(BOOL)bold ofSize:(CGFloat)size;
- (void)setAttributedText:(NSString * _Nonnull)newText bold:(BOOL)bold ofSize:(CGFloat)size verticalOffset:(CGFloat)verticalOffset;
@end


SWIFT_CLASS("_TtC7WDBrand35UILabelStyledNoIntrinsicContentSize")
@interface UILabelStyledNoIntrinsicContentSize : UILabelStyled
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand18UIPickerViewStyled")
@interface UIPickerViewStyled : UIPickerView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand17UISearchBarStyled")
@interface UISearchBarStyled : UISearchBar
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
@property (nonatomic, strong) UIColor * _Nullable searchFieldBackgroundColor;
@property (nonatomic, strong) UIColor * _Nullable textColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7WDBrand17UIStackViewStyled")
@interface UIStackViewStyled : UIStackView
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand14UISwitchStyled")
@interface UISwitchStyled : UISwitch
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class NSBundle;
@protocol UIViewControllerTransitionCoordinator;

SWIFT_CLASS("_TtC7WDBrand24UITabBarControllerStyled")
@interface UITabBarControllerStyled : UITabBarController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
@end


SWIFT_CLASS("_TtC7WDBrand21UITableViewCellStyled")
@interface UITableViewCellStyled : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC7WDBrand17UITableViewStyled")
@interface UITableViewStyled : UITableView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UITextFieldDelegate;

SWIFT_CLASS("_TtC7WDBrand17UITextFieldStyled")
@interface UITextFieldStyled : UITextField
@property (nonatomic, copy) NSString * _Nonnull customFontName;
@property (nonatomic) UIEdgeInsets edgeInsets;
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull translationKey;
@property (nonatomic, strong) UIColor * _Nullable placeholderColor;
@property (nonatomic, strong) UIImage * _Nullable placeholderImage;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL borderTop;
@property (nonatomic) BOOL borderLeft;
@property (nonatomic) BOOL borderRight;
@property (nonatomic) BOOL borderBottom;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) BOOL isValidated;
@property (nonatomic) BOOL isShowingError;
@property (nonatomic, strong) id <Formattable> _Nullable formatterDelegate;
@property (nonatomic, strong) id <UITextFieldDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable placeholder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (void)setupUXSpecificProperties;
- (void)setFonts;
- (void)setNeedsStyle;
- (void)textFieldChanged:(NSNotification * _Nullable)notification;
- (NSString * _Nonnull)getTextWithoutFormatting:(NSString * _Nonnull)textWithFormatting SWIFT_WARN_UNUSED_RESULT;
- (void)formatTextField:(UITextFieldStyled * _Nonnull)textField;
- (void)setValidateWhileEditing:(NSString * _Nonnull)regex;
- (void)setValidateAfterEditing:(NSString * _Nonnull)regex;
- (BOOL)validate:(BOOL)shouldHandleErrorStyle SWIFT_WARN_UNUSED_RESULT;
@end


@interface UITextFieldStyled (SWIFT_EXTENSION(WDBrand)) <UITextFieldDelegate>
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP7WDBrand25UITextFieldStyledDelegate_")
@protocol UITextFieldStyledDelegate <UITextFieldDelegate>
- (void)textFieldDidChange:(UITextFieldStyled * _Nonnull)textField;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC7WDBrand16UITextViewStyled")
@interface UITextViewStyled : UITextView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=7.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIView (SWIFT_EXTENSION(WDBrand))
- (void)setCustomAccessibilityLabel:(NSString * _Nullable)accessibilityLabel;
@end


@interface UIView (SWIFT_EXTENSION(WDBrand))
- (void)applyBranding:(NSString * _Nullable)keyPath;
@end


SWIFT_CLASS("_TtC7WDBrand12UIViewStyled")
@interface UIViewStyled : UIView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC7WDBrand15UIWebViewStyled")
@interface UIWebViewStyled : UIWebView
@property (nonatomic, copy) NSString * _Nonnull styleKeyPath;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WDBrand23WDCInputWithErrorStyled")
@interface WDCInputWithErrorStyled : UIStackView
@property (nonatomic, copy) NSString * _Nonnull textFieldStyleKeyPath;
@property (nonatomic, copy) NSString * _Nonnull textFieldTranslationKey;
@property (nonatomic, strong) UITextFieldStyled * _Nonnull textField;
@property (nonatomic) CGFloat textFieldCornerRadius;
@property (nonatomic, strong) UILabelStyled * _Nonnull errorLabel;
@property (nonatomic, strong) UIColor * _Nonnull errorColor;
@property (nonatomic, readonly) BOOL hasError;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)showError;
- (void)showErrorWith:(NSString * _Nullable)text;
- (void)hideError;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
